#!/usr/bin/env bash

while getopts ":hpsx" opt;
do
  case $opt in
    h)

# check for package installer script and execute it
if [[ -x ./package_installer ]];
then
  echo "running package installer script"
  ./package_installer
else
  echo "package_installer not found or executable"
  exit 1
fi



#check symlink script and execute it
#then echo "Running symlink creation script"
if [[ -x ./symlink_script ]];
then
  echo "Running symlink creation script"
  ./config_symlink
else
  echo "symlink_script not found or not executable"
  exit 1
fi

echo "Configuration setup complete"
