#!/usr/bin/env bash

# File: main_script
#
# Description: This script is used to interact with the other files and scripts for the configuration. It is used to call the other two scripts as required.
#
# Author: Alfred Chan
# Date: Nov 8, 2024
# Source: https://www.oreilly.com/videos/bash-shell-scripting/9780137689064/9780137689064-BSS2_04_10_01/ | 10.1 Working with Options
#

# user function that displays information on how to use the script. It is shown when user types an invalid input or when requested
function usage(){
  echo "Usage: ./main_script [-i info] [-p package installer] [-s creates symbolic links] [-x executes both scripts]"
  exit 1
}

# help message shown to describe what the script actually does
function helpmessage(){
  echo "main_script is a script that helps you install packages and configures files by creating symbolic links between a file's remote location in the user's home directory and its actual location."
  echo "-i displays this help message as well as how to use it (usage message)."
  echo "-p will run the package_installer script which installs the packages located within packages.txt"
  echo "-s will run the symlink_script which creates symbolic links for the config files."
  echo "-x will execute and run both the package_installer script and the symlink_script script."
}

# used to get the options from the user's command-line at the time of calling the script and output what the user wants the script to perform
# refer to usage and helpmessage functions to know what each 
while getopts "ipsx" opt; do
  case $opt in
    # displays the help message and how to use the script
    i) helpmessage
      usage;;
    # runs the package_installer script
    p) ./package_installer;;
    # runs the symlink_script script
    s) ./symlink_script;;
    # runs both the package_installer and symlink_script scripts
    x) ./package_installer && ./symlink_script;;
  esac
# we reset the index of the arguments in the options in case we need to call it again
shift $((OPTIND -1))
done

# checks if the script was called with an argument, if not, output error message and echo usage function
if [[ -z "$1" ]];
then
  echo "No arguments have been provided"
  usage
fi

# checks if there is more than one argument called, if so, then output error message and echo usage function
if [[ -n "$2" ]];
then
  echo "Too many arguments provided"
  usage
fi

